word_link.settings:
  type: config_object
  label: 'Word Links settings'
  mapping:
    word_link_content_types:
      label: Content types
      type: sequence
      sequence:
        type: string
    word_link_tags_except:
      type: string
      label: 'word_link_tags_except'
    word_link_reg_all:
      type: string
      label: 'word_link_reg_all'
    word_link_reg_words_only:
      type: string
      label: 'word_link_reg_words_only'
    word_link_wrap_tag:
      type: string
      label: 'word_link_wrap_tag'
    word_link_highlight:
      type: boolean
      label: 'word_link_highlight'
    word_link_page_max_links:
      type: integer
      label: 'word_link_page_max_links'